---
- name: Generate root passwords for all MaaS nodes
  hosts: maas
  vars:
    PASSWD_FILE: maas-host-root-passwords.txt
    PASSWD_LENGTH: 12
  tasks:
    - name: generate root password
      local_action: shell pwgen {{ PASSWD_LENGTH }} 1
      register: root_pass

    - name: ensure that password file exists
      local_action: file path="{{ PASSWD_FILE }}" state=touch
      
    - name: output password to file
      local_action: 'lineinfile dest="{{ PASSWD_FILE }}" regexp="^{{ inventory_hostname | upper }}(.*)" line="{{ inventory_hostname | upper }}: {{ root_pass.stdout }}"'

    - name: retrieve password from file
      local_action: shell cat {{ PASSWD_FILE }} | grep {{ inventory_hostname | upper }} | cut -f 2 -d ' '
      register: pass_from_file
      tags:
        - pass-change

    - name: encrypt generated root password
      local_action: shell python -c "from passlib.hash import sha512_crypt; import getpass; print sha512_crypt.encrypt('{{ pass_from_file.stdout }}')"
      register: encrypted_pass

    - name: the root password will be set to the following
      debug: msg='{{ pass_from_file.stdout }}'
      tags:
        - pass-change

    - name: change root password
      user: name=root password="{{ encrypted_pass.stdout }}"
      when: pass_from_file.stdout != ""
      tags:
        - pass-change