---

- name: install cinder storage dependencies
  apt: name={{ item }} state=present
  with_items: CINDER_STORAGE_CONFIG.packages
  tags:
    - install

# /sbin/parted /dev/sda -s mklabel gpt
# /sbin/parted /dev/sda -s mkpart primary 0% 100%
# /sbin/parted /dev/sda -s set 1 lvm on
# parted /dev/sda -s p

- name: template cinder.conf
  template: src="{{ CINDER_STORAGE_CONFIG.cinder_conf.template }}" dest="{{ CINDER_STORAGE_CONFIG.cinder_conf.dest }}" backup=yes
  tags:
    - cinder
    - template

- name: template lvm.conf
  template: src="{{ CINDER_STORAGE_CONFIG.lvm_conf.template }}" dest="{{ CINDER_STORAGE_CONFIG.lvm_conf.dest }}" backup=yes
  tags:
    - lvm
    - template

- name: create the LVM physical volume
  lvg: vg={{ CINDER_STORAGE_CONFIG.lvm.volume_group_name }} pvs=/dev/{{ CINDER_STORAGE_CONFIG.lvm.physical_volume }} vg_options="--metadatasize {{ CINDER_STORAGE_CONFIG.lvm.metadatasize }}"
  tags:
    - lvm

- name: restart block storage services
  service: name={{ item }} state=restarted enabled=yes
  with_items: CINDER_STORAGE_CONFIG.services
  tags:
    - block-storage-service-restart

- name: remove /var/lib/cinder/cinder.sqlite
  file: path=/var/lib/cinder/cinder.sqlite state=absent
  tags:
    - cleanup
